//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viking_Rejser.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Viking_Rejser1Entities1 : DbContext
    {
        public Viking_Rejser1Entities1()
            : base("name=Viking_Rejser1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kunder> Kunder { get; set; }
        public virtual DbSet<Rejsearrangement> Rejsearrangement { get; set; }
        public virtual DbSet<Tilmelding> Tilmelding { get; set; }
        public virtual DbSet<Transportører> Transportører { get; set; }
    }
}
