//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viking_Rejser.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rejsearrangement
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Town { get; set; }
        public string Start_date { get; set; }
        public string End_date { get; set; }
        public string Max_participants { get; set; }
        public string Transporter { get; set; }
        public string Price_per_participant { get; set; }
        public string Travel_registrations { get; set; }
        public string Description { get; set; }
    
        public virtual Tilmelding Tilmelding { get; set; }
        public virtual Transportører Transportører { get; set; }
    }
}
